local Scheduler = require('systems.scheduler')

local function joined(list) return table.concat(list, ',') end

test('cancels later callbacks and defers additions during dispatch', function()
    local clock = Scheduler.new(0.25)
    local calls, cancel = {}, function() end
    clock:after(0, function()
        calls[#calls + 1] = 'first'; cancel()
        clock:after(0, function() calls[#calls + 1] = 'new' end)
    end)
    cancel = clock:after(0, function() calls[#calls + 1] = 'cancelled' end)
    clock:advance()
    eq(joined(calls), 'first')
    clock:advance()
    eq(joined(calls), 'first,new')
end)

test('rounds deadlines up, recurs and releases cancelled work', function()
    local clock = Scheduler.new(0.25)
    local count = 0
    local cancel = clock:every(0.3, function() count = count + 1 end)
    clock:advance(); eq(count, 0)
    clock:advance(); eq(count, 1)
    clock:advance(); clock:advance(); eq(count, 2)
    cancel(); cancel()
    clock:advance(); clock:advance(); eq(count, 2)
    eq(clock:getPending(), 0); eq(clock:getTick(), 6); eq(clock:getElapsed(), 1.5); eq(clock:getStep(), 0.25)
    clock:dispose(); clock:dispose()
    failsAt(function() clock:after(1, function() end) end, 'Scheduler.after: the scheduler is disposed')
    failsAt(function() clock:every(1, function() end) end, 'Scheduler.every: the scheduler is disposed')
    clock:advance(); eq(clock:getTick(), 6)
end)

test('a failing task is cancelled and reported; advancing during a tick raises', function()
    local messages = {}
    local clock = Scheduler.new(1, function(message) messages[#messages + 1] = message end)
    local later = 0
    clock:every(1, function() clock:advance() end)
    clock:after(1, function() later = later + 1 end)
    clock:advance(); clock:advance()
    eq(#messages, 1)
    assert(messages[1]:find('Scheduler.advance: cannot advance during a tick', 1, true), messages[1])
    eq(later, 1); eq(clock:getPending(), 0); eq(#PRINTED, 0)
end)

test('without onError a failure is printed', function()
    local clock = Scheduler.new(1)
    clock:after(1, function() error('intentional scheduler probe') end)
    clock:advance()
    eq(#PRINTED, 1)
    assert(PRINTED[1]:find('[systems] Scheduler task failed:', 1, true), PRINTED[1])
    assert(PRINTED[1]:find('intentional scheduler probe', 1, true), PRINTED[1])
end)

test('tick rounding absorbs float error in non power-of-two steps', function()
    local clock = Scheduler.new(0.01)
    eq(clock:ticks(0.07), 7); eq(clock:ticks(0.071), 8); eq(clock:ticks(0), 1)
    failsAt(function() clock:ticks(-1) end, 'Scheduler.ticks: expected a finite non-negative delay')
end)

test('the heap runs due tasks by deadline, then creation order, and removes mid-heap tasks', function()
    local clock = Scheduler.new(1)
    local order = {}
    clock:after(3, function() order[#order + 1] = 'c3' end)
    clock:every(1, function() order[#order + 1] = 'r1' end)
    clock:after(1, function() order[#order + 1] = 'a1' end)
    local cancel = clock:after(2, function() order[#order + 1] = 'cancelled' end)
    clock:after(2, function() order[#order + 1] = 'b2' end)
    for index = 0, 19 do clock:after(5 + index % 3, function() end) end
    cancel()
    clock:advance(); clock:advance(); clock:advance()
    eq(joined(order), 'r1,a1,r1,b2,c3,r1')
    eq(clock:getPending(), 21)
end)

test('dispose during a tick stops the rest of the tick', function()
    local clock = Scheduler.new(1)
    local ran = {}
    clock:after(1, function() ran[#ran + 1] = 'first'; clock:dispose() end)
    clock:after(1, function() ran[#ran + 1] = 'second' end)
    clock:advance()
    eq(joined(ran), 'first'); eq(clock:getPending(), 0)
end)

test('arguments are checked at the caller', function()
    failsAt(function() Scheduler.new(0) end, 'Scheduler.new: expected a finite positive step')
    failsAt(function() Scheduler.new(-1) end, 'Scheduler.new: expected a finite positive step')
    failsAt(function() Scheduler.new(math.huge) end, 'Scheduler.new: expected a finite positive step')
    failsAt(function() Scheduler.new('1') end, 'Scheduler.new: expected a finite positive step')
    failsAt(function() Scheduler.new(1, 5) end, 'Scheduler.new: expected a callback function')
    local clock = Scheduler.new()
    eq(clock:getStep(), 1 / 32)
    failsAt(function() clock:after(-1, function() end) end, 'Scheduler.after: expected a finite non-negative delay')
    failsAt(function() clock:after(0 / 0, function() end) end, 'Scheduler.after: expected a finite non-negative delay')
    failsAt(function() clock:after(1, nil) end, 'Scheduler.after: expected a callback function')
    failsAt(function() clock:every(0, function() end) end, 'Scheduler.every: expected a finite positive interval')
    failsAt(function() clock:every(1, 'x') end, 'Scheduler.every: expected a callback function')
    failsAt(function() Scheduler.advance({}) end, 'Scheduler.advance: expected Scheduler')
    failsAt(function() Scheduler.after({}, 1, print) end, 'Scheduler.after: expected Scheduler')
    eq(clock:getPending(), 0)
end)

test('start drives advance from one periodic timer; stop and dispose destroy it', function()
    local timers = {}
    native('CreateTimer', function()
        local timer = {}
        timers[#timers + 1] = timer
        return timer
    end)
    native('TimerStart', function(timer, timeout, periodic, fn)
        timer.timeout, timer.periodic, timer.fn = timeout, periodic, fn
    end)
    native('PauseTimer', function() end)
    native('DestroyTimer', function(timer) timer.destroyed = true end)
    local clock = Scheduler.new(0.5)
    local runs = 0
    clock:every(0.5, function() runs = runs + 1 end)
    local stop = clock:start()
    eq(#timers, 1); eq(timers[1].timeout, 0.5); eq(timers[1].periodic, true)
    failsAt(function() clock:start() end, 'Scheduler.start: already started')
    timers[1].fn(); timers[1].fn()
    eq(clock:getTick(), 2); eq(runs, 2)
    stop(); stop()
    eq(timers[1].destroyed, true); eq(callCount('DestroyTimer'), 1)
    local stopAgain = clock:start()
    eq(#timers, 2)
    stop()
    eq(timers[2].destroyed, nil)
    clock:dispose()
    eq(timers[2].destroyed, true)
    stopAgain()
    eq(callCount('DestroyTimer'), 2)
    failsAt(function() clock:start() end, 'Scheduler.start: the scheduler is disposed')
    failsAt(function() Scheduler.start({}) end, 'Scheduler.start: expected Scheduler')
end)
